spring:
  application:
    name: user_center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: ysq666666

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false  # 关闭驼峰转下划线

logging:
  level:
    com.zhangguoye.security: info